version: '3'
services:
  strapi:
    container_name: StrapiCMS
    image: strapi/strapi
    environment:
      VIRTUAL_HOST: admin.tsuntsun.moe
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: S@xi0n!
    links:
      - postgres:postgres
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'

  postgres:
    container_name: PostgreSQL
    image: postgres
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: S@xi0n!
    volumes:
      - ./data:/data/postgres
    ports:
      - '5432:5432'

  httpd:
    container_name: ApacheWebserver
    environment:
      VIRTUAL_HOST: tsuntsun.moe
    ports:
      - '5000:80'
    volumes:
      - './WWW/:/usr/local/apache2/htdocs/'
    image: 'httpd:2.4'


  nginx-proxy:
    container_name: NginxReverseProxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    container_name: WoamiContainer
    image: jwilder/whoami
    environment:
       - VIRTUAL_HOST=whoami.local


  portainer:
    ports:
       - '8000:8000'
       - '9000:9000'
    container_name: portainer
    restart: always
    volumes:
       - '/var/run/docker.sock:/var/run/docker.sock'
       - './portainer_data:/data'
    image: portainer/portainer
